'''This is Fake News Headline Generator. '''
''' "IT WILL EVOLVE AS I LEARN MORE" '''
'''Only Created names and other 3 categories from chatgpt to have more variety.'''

import random as rd
import os

os.system("cls")

input("\n<This program will create some random news headline like today's world\> ! \n\n_Dont Take it 'SERIOUSLY'_ \n  \n ---Press 'Enter' to Continue---\n")

subjects = [
    "Narendra Modi",
    "Rahul Gandhi",
    "Amit Shah",
    "Arvind Kejriwal",
    "Mamata Banerjee",
    "Yogi Adityanath",
    "Donald Trump",
    "Joe Biden",
    "Vladimir Putin",
    "Kim Jong Un",
    "Elon Musk",
    "Mark Zuckerberg",
    "Local MLA",
    "Opposition Leader",
    "Finance Minister",
    "Cricketer Virat Kohli",
    "Bollywood Star Salman Khan",
    "Fake Baba",
    "News Anchor",
    "School Principal",
    "Startup Founder",
    "Tech YouTuber",
    "College Professor",
    "Neighbour Uncle",
    "Retired Army Officer",
    "Street Food Vendor",
    "Rickshaw Puller",
    "Metro Passenger",
    "Online Gamer",
    "Instagram Influencer",
    "Twitter Troll",
    "WhatsApp Admin",
    "Local Shopkeeper",
    "Temple Priest",
    "Astrologer",
    "Gym Trainer",
    "Zomato Delivery Boy",
    "Ola Driver",
    "Swiggy Rider",
    "Cab Passenger",
    "College Student",
    "Engineering Dropout",
    "Medical Student",
    "Lawyer",
    "Judge",
    "Police Constable",
    "IPS Officer",
    "School Teacher",
    "Angry Parent",
    "Curious Child",
    "Grandmother",
    "Grandfather",
    "Cricket Umpire",
    "Football Coach",
    "Kabaddi Player",
    "Olympic Sprinter",
    "Chess Champion",
    "Wrestler",
    "Boxer",
    "Bollywood Director",
    "South Indian Actor",
    "Hollywood Actor",
    "Pop Singer",
    "Rock Band Member",
    "DJ",
    "Standup Comedian",
    "Meme Creator",
    "Cartoon Character Doraemon",
    "Nobita",
    "Shinchan",
    "Chhota Bheem",
    "Motu",
    "Patlu",
    "Tom",
    "Jerry",
    "Mickey Mouse",
    "Donald Duck",
    "Scooby Doo",
    "Harry Potter",
    "Hermione",
    "Ron Weasley",
    "Draco Malfoy",
    "Batman",
    "Superman",
    "Spider-Man",
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Loki",
    "Black Widow",
    "Doctor Strange",
    "Shaktimaan",
    "Power Ranger Red",
    "Power Ranger Blue",
    "Pokemon Ash",
    "Pikachu",
    "Bulbasaur",
    "Charizard",
    "Squirtle",
    "Naruto",
    "Sasuke",
    "Goku",
    "Vegeta",
    "Piccolo",
    "Saitama",
    "Light Yagami",
    "L (Death Note)",
    "Anime Fan",
    "K-Pop Idol",
    "BTS Fan",
    "Army Fan Girl",
    "K-Drama Actor",
    "Netflix Subscriber",
    "Amazon Prime Viewer",
    "Hotstar Binger",
    "Cricket Commentator",
    "Sports Journalist",
    "Film Critic",
    "News Editor",
    "Radio Jockey",
    "Fashion Model",
    "Hairstylist",
    "Makeup Artist",
    "Tattoo Artist",
    "Painter",
    "Photographer",
    "Wildlife Explorer",
    "Zookeeper",
    "Dog Lover",
    "Cat Owner",
    "Parrot Seller",
    "Fisherman",
    "Farmer",
    "Agriculture Scientist",
    "Space Scientist",
    "ISRO Engineer",
    "NASA Astronaut",
    "Space Tourist",
    "UFO Believer",
    "Flat Earth Theorist",
    "Conspiracy Theorist",
    "Climate Activist",
    "NGO Worker",
    "Social Media Activist",
    "Political Analyst",
    "Economist",
    "Stock Market Trader",
    "Bitcoin Investor",
    "Crypto Scammer",
    "Startup CEO",
    "Venture Capitalist",
    "Angel Investor",
    "Failed Entrepreneur",
    "Tech Blogger",
    "Cyber Security Expert",
    "Ethical Hacker",
    "Dark Web Seller",
    "AI Researcher",
    "ChatGPT User",
    "Python Developer",
    "Java Programmer",
    "C++ Coder",
    "Rust Enthusiast",
    "Open Source Contributor",
    "Freelancer",
    "Remote Worker",
    "Call Center Employee",
    "BPO Manager",
    "HR Recruiter",
    "CEO",
    "CFO",
    "CTO",
    "Intern",
    "Part-Time Worker",
    "Delivery Drone Operator",
    "Gamer Kid",
    "Esports Champion",
    "Stream Sniper",
    "Twitch Streamer",
    "YouTube Vlogger",
    "Instagram Reeler",
    "TikTok Star",
    "Shorts Creator",
    "OTT Actor",
    "Reality Show Contestant",
    "Bigg Boss Housemate",
    "Roadies Contestant",
    "KBC Participant",
    "Joker",
    "Clown",
    "Circus Ringmaster",
    "Magician",
    "Street Dancer",
    "Background Dancer",
    "Wedding Photographer",
    "Bridegroom",
    "Bride",
    "Best Man",
    "Maid of Honor",
    "Pandit Ji",
    "Barber",
    "Milkman",
    "Vegetable Seller",
    "Fruit Vendor",
    "Tea Seller",
    "Pan Shop Owner",
    "Auto Driver",
    "Traffic Police",
    "Postman",
    "Courier Guy",
    "Bank Manager",
    "Loan Officer",
    "ATM Guard",
    "Shop Cashier",
    "Supermarket Manager",
    "Mall Shopper",
    "Window Shopper",
    "Rich Businessman",
    "Poor Farmer",
    "Middle Class Employee",
    "Unemployed Graduate",
    "Angry Customer",
    "Happy Customer",
    "Confused Tourist",
    "Lost Traveller",
    "Backpacker",
    "Adventure Rider",
    "Cyclist",
    "Bike Rider",
    "Car Owner",
    "Bus Conductor",
    "Train Passenger",
    "Pilot",
    "Flight Attendant",
    "Airport Security",
    "Customs Officer",
    "Smuggler",
    "Pirate",
    "Fictional Villain Joker",
    "Thanos",
    "Ultron",
    "Darth Vader",
    "Stormtrooper",
    "Obi-Wan Kenobi",
    "Yoda",
    "Baby Yoda",
    "Han Solo",
    "Luke Skywalker",
    "Princess Leia",
    "Game of Thrones Jon Snow",
    "Daenerys",
    "Tyrion Lannister",
    "Cersei Lannister",
    "Arya Stark",
    "Sansa Stark",
    "Bran Stark",
    "Night King",
    "Hodor",
    "Dragon Rider",
    "Zombie",
    "Vampire",
    "Werewolf",
    "Ghost",
    "Witch",
    "Wizard",
    "Fairy",
    "Mermaid",
    "Alien",
    "Robot",
    "AI Assistant",
    "Cloned Human",
    "Mad Scientist",
    "Evil Genius",
    "Crazy Inventor",
    "Time Traveller",
    "Future Kid",
    "Past King",
    "Historical Emperor Akbar",
    "Raja Harishchandra",
    "Rani Laxmibai",
    "Maharana Pratap",
    "Shivaji Maharaj",
    "Ashoka The Great",
    "British Officer",
    "Freedom Fighter Bhagat Singh",
    "Subhas Chandra Bose",
    "Mahatma Gandhi",
    "Jawaharlal Nehru",
    "Indira Gandhi",
    "Rajiv Gandhi",
    "APJ Abdul Kalam",
    "Dr. B R Ambedkar",
    "Swami Vivekananda",
    "Chanakya",
    "Kabir Das",
    "Tulsidas",
    "Kalidasa",
    "Rabindranath Tagore",
    "Chetan Bhagat",
    "Arundhati Roy",
    "R K Narayan",
    "Ruskin Bond",
    "William Shakespeare",
    "Charles Dickens",
    "Mark Twain",
    "George Orwell",
    "J K Rowling",
    "Stephen King",
    "Agatha Christie",
    "Dan Brown",
    "Paulo Coelho",
    "Philosopher Socrates",
    "Aristotle",
    "Plato",
    "Einstein",
    "Newton",
    "Galileo",
    "Nikola Tesla",
    "Thomas Edison",
    "Marie Curie",
    "Charles Darwin",
    "Steve Jobs",
    "Bill Gates",
    "Sundar Pichai",
    "Satya Nadella",
    "Jeff Bezos",
    "Jack Ma",
    "Mukesh Ambani",
    "Gautam Adani",
    "Ratan Tata",
    "Azim Premji",
    "Infosys Founder Narayana Murthy",
    "Wipro CEO",
    "Tech Mahindra CEO",
    "TCS CEO",
    "Reliance Jio Chairman",
    "Flipkart Founder",
    "Ola Founder",
    "Paytm Founder",
    "BYJU's Teacher",
    "Unacademy Educator",
    "PhysicsWallah Teacher",
    "Vedantu Teacher",
    "Coursera Student",
    "Udemy Instructor",
    "Khan Academy Learner"
]

actions = ["accidentally bans",
        "secretly launches",
        "announces",
        "denies",
        "leaks",
        "forgets",
        "protests against",
        "unveils",
        "eats",
        "dances with",
        "declares",
        "argues about",
        "tweets about",
        "misplaces",
        "exposes",
        "celebrates",
        "investigates",
        "launches",
        "shuts down",
        "complains about"]
places = ["Delhi",
        "Mumbai",
        "Lucknow",
        "Kolkata",
        "Chennai",
        "Bangalore",
        "Hyderabad",
        "Rajasthan desert",
        "Ladakh border",
        "UP Assembly",
        "Lok Sabha",
        "White House",
        "Red Fort",
        "Airport lounge",
        "Tea stall",
        "Cricket stadium",
        "Railway station",
        "Local park",
        "Space station",
        "Random WhatsApp group"
        ]
objects = ["budget proposal",
        "secret deal",
        "trade ban",
        "protest march",
        "viral meme",
        "controversial tweet",
        "election campaign rally",
        "new policy draft",
        "cabinet reshuffle",
        "fake news story",
        "security breach",
        "parliament fight",
        "tax hike announcement",
        "fuel price rise",
        "public holiday declaration",
        "cricket match controversy",
        "scam investigation",
        "billion-dollar project",
        "corruption scandal",
        "UN meeting speech",
        "diplomatic handshake",
        "space mission launch",
        "airport chaos",
        "traffic jam protest",
        "power outage",
        "data leak",
        "new tech gadget release",
        "climate summit",
        "celebrity endorsement",
        "statue inauguration",
        "airport runway dance",
        "press conference blunder",
        "broken mic incident",
        "food shortage warning",
        "new law proposal",
        "accidental WhatsApp forward",
        "AI robot announcement",
        "election poster misprint",
        "mysterious suitcase"]
all_headlines = []
while True:

    headline =f"⭕ BREAKING NEWS ⭕ : {rd.choice(subjects)} {rd.choice(actions)} {rd.choice(objects)} in {rd.choice(places)} !"
    os.system("cls")

    print(headline)
    print("\n\n")
    all_headlines.append(headline)

    choice = input("Would u like to see more or that's it ! \n(Enter N to Stop.)").strip().lower()

    if choice == "n":
        break
os.system("cls")
print("All Generated Headlines : -\n")
for i ,h in enumerate(all_headlines , start = 1):
    print(f"{h} : {i}")
print("\n\n\n😂 Hope u had a Gaggle! \n\n\n🎭")

